# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='visit.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bvisit.proto\"L\n\x0cVisitMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\ncoordinate\x18\x02 \x01(\t\x12\x15\n\rcreation_time\x18\x03 \x01(\t26\n\x0cVisitService\x12&\n\x06\x43reate\x12\r.VisitMessage\x1a\r.VisitMessageb\x06proto3'
)




_VISITMESSAGE = _descriptor.Descriptor(
  name='VisitMessage',
  full_name='VisitMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='person_id', full_name='VisitMessage.person_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='VisitMessage.coordinate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='VisitMessage.creation_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['VisitMessage'] = _VISITMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisitMessage = _reflection.GeneratedProtocolMessageType('VisitMessage', (_message.Message,), {
  'DESCRIPTOR' : _VISITMESSAGE,
  '__module__' : 'visit_pb2'
  # @@protoc_insertion_point(class_scope:VisitMessage)
  })
_sym_db.RegisterMessage(VisitMessage)



_VISITSERVICE = _descriptor.ServiceDescriptor(
  name='VisitService',
  full_name='VisitService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='VisitService.Create',
    index=0,
    containing_service=None,
    input_type=_VISITMESSAGE,
    output_type=_VISITMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISITSERVICE)

DESCRIPTOR.services_by_name['VisitService'] = _VISITSERVICE

# @@protoc_insertion_point(module_scope)
